name: Deployment Prep
on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  config:
    permissions:
      contents: write  # for stefanzweifel/git-auto-commit-action to push code in repo
    if: github.repository == 'anuraghazra/github-readme-stats'
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
        with:
          egress-policy: audit

      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Deployment Prep
        run: python ./.github/workflows/deploy-prep.py
      - uses: stefanzweifel/git-auto-commit-action@3ea6ae190baf489ba007f7c92608f33ce20ef04a # v4.16.0
        with:
          branch: vercel
          create_branch: true
          push_options: "--force"
