name: "Pull Request Labeler"
on:
  - pull_request_target

permissions:
  contents: 'read'
  id-token: 'write'
  issues: 'write' #__This should fixe the HttpError: Resource not accessible by integration

jobs:
  triage:
    if: github.repository == 'meyer-pidiache/github-readme-stats'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.G_TOKEN }}"
