name: "Pull Request Labeler"
on:
  - pull_request_target

permissions:
  contents: 'read'
  pull-requests: 'write'

jobs:
  triage:
    if: github.repository == 'meyer-pidiache/github-readme-stats'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.G_TOKEN }}"
